-- + SECUENCIAS

-- El serial crea una secuencia.
create table "users" (
    "user_id" SERIAL PRIMARY KEY,
    "username" VARCHAR
)

-- Lista de secuencias.
SELECT
    pc.relname,
    ps.seqstart,
    ps.seqincrement,
    ps.seqmax,
    ps.seqmin,
    ps.seqcache,
    ps.seqcycle
FROM
    pg_class pc
    JOIN pg_sequence ps ON pc.oid = ps.seqrelid;


-- + IDENTITY.

-- Crea un identity
create table "users2" (
    "user_id" INTEGER GENERATED by DEFAULT as IDENTITY PRIMARY KEY,
    "username" VARCHAR
);

-- Crea un identity pero restringido al colocar un valor pordefecto
create table "users3" (
    "user_id" INTEGER GENERATED ALWAYS as IDENTITY PRIMARY KEY,
    "username" VARCHAR
);

-- Crea un identity pero inciado desde 100 y cuenta de dos en dos.
create table "users4" (
    "user_id" INTEGER GENERATED ALWAYS as IDENTITY (START WITH 100 INCREMENT BY 2) PRIMARY KEY,
    "username" VARCHAR
);

-- Es mas recomendable el identity por lo que se puede tener mas control.