version: '3'

services:
# Imagen de base de datos.
  myDB:
    image: postgres:15.3
    container_name: my-database # Nombre del contenedor.
    restart: always 
    ports:
      - 5432:5432 # Puerto por defecto de postgres SQL.
    environment: # Variables de entorno.
      - POSTGRES_USER=alumno # Usuario de base de datos.
      - POSTGRES_PASSWORD=123456 # Password de la base de datos.
      - POSTGRES_DB=course-db # El nombre de la base de datos.
    volumes:
      - ./postgres:/var/lib/postgresql/data

# Visor de base de datos.
  pdAdmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    depends_on:
      - myDB # depende myDB para poderse levantar.
    ports:
      - 8080:80 # Puerto por defecto de la maquina con el puerto del contenedor.
    environment: # Variables de entorno.
      - PGADMIN_DEFAULT_EMAIL=alumno@google.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    volumes:
      - ./pgadmin:/var/lib/pgadmin
      - ./pgadmin:/certs/server.cert
      - ./pgadmin:/certs/server.key
      - ./pgadmin:/pgadmin4/servers.json